game:
  initial_tiles_per_player: 13

rules:
  cheat_command_enabled: true
  score_usage: true
  joker_usage: true

  initial_meld_value: 30 # Minimum value of the initial meld to be played
  time_limit_per_turn: 120 # Time limit in seconds for each player's turn

tiles:
  sets:
    - color: "red"
      count: 2
      range: [1, 13]
    - color: "blue"
      count: 2
      range: [1, 13]
    - color: "yellow"
      count: 2
      range: [1, 13]
    - color: "green"
      count: 2
      range: [1, 13]
  jokers:
    count: 2
    colors:
      - "green"
      - "red"

file_saving:
  save_game_on_exit: true
  default_saving_path: "rummikub_save.json"
